spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    serialization:
      indent_output: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  thymeleaf:
    mode: html
    encoding: UTF-8
    cache: false
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.zy.**.model
  mapper-locations: classpath:com/zy/**/repository/*Mapper.xml
  global-config:
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    id-type: 0

server:
  port: 8060
  
logging:
  path: ./log
  level:
    root: INFO  


 
    
