spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid: 
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      alidation-query: SELECT 'x'
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      filters: stat,wall
      stat-view-servlet.url-pattern: /druid/*
      stat-view-servlet.reset-enable: true
      stat-view-servlet.login-username: admin
      stat-view-servlet.login-password: admin
      aop-patterns: com.zy.admin.*.service.*
  jackson:
    serialization:
      indent_output: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  thymeleaf:
    mode: html
    encoding: UTF-8
    cache: false
    
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.zy.**.model
  mapper-locations: classpath:com/zy/**/repository/*Mapper.xml
  global-config:
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    id-type: 0
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,mappings
      base-path: /monitor

server:
  port: 8060
  servlet:
    session: 
      timeout: 1800
  
logging:
  path: ./log
  level:
    com.zy.admin.business.repository: DEBUG
    root: INFO  

shz:
  security:
    imageCode:
      length: 4 
      open: false
 
    
